### ISSUE TITLE
Convert package names to lowercase

### ISSUE THREAD

**Issue by csabakoncz** [Clearsight-github/DictionaryWithTime#5]
The Java code convention recommends to have lowercase package names:
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

(So here: https://github.com/Clearsight-github/DictionaryWithTime/blob/master/src/Main/Main.java#L1
```package Main;```
should be rather
```package main;```
)

**Comment by Clearsight-github** [comment]
Fixed.

**Comment by Clearsight-github** [comment]
<img width="212" alt="package1" src="https://cloud.githubusercontent.com/assets/27925373/25524123/79fa4604-2c09-11e7-9cb4-ef08716947a1.png">
I see this. I try to figure it out why.

**Comment by Clearsight-github** [comment]
I renamed both directory with +1 and now it seems to work well.
