### ISSUE TITLE
 listFunction = input.nextLine(); in line 49 sees an extra command

### ISSUE THREAD

**Issue by Clearsight-github** [Clearsight-github/DictionaryWithTime#6]
When the user finished a new list or expanded a list for some reason 
 listFunction = input.nextLine(); in line 49
 think that an empty line command is given to it and so that go to default case and rerun a cycle in 
do-while repeating the first sysout.

**Comment by csabakoncz** [comment]
A unit test would now come handy to demonstrate the issue.

**Comment by Clearsight-github** [comment]
Please enter a command: 
"input" or 
"list" or 
"search" or 
"end"
**input**
Choose from the list: 
"new" for a new list or 
"exist" to continue an existing list or 
"back" to go back to main menu.
**exist**
Open a file to read and write...

.classpath
.git
.gitignore
.project
.settings
bin
LICENSE
new - Copy.txt
new.txt
new2.txt
new3.txt
pom.xml
src
target
ToDo.txt
Give me the file name what you want to continue to extend "fileName.txt": 
**new3.txt**
File has chosen. Reading lines from the file and filling the ArrayList

Printing out the existing list from ArrayList to the screen
[ 01:01:01 apple alma
,  02:02:02 hat sapka
]
Write words to input.
You can type your time and words now:
hh:mm:ss foreign_word mother_tongue_word [or type "back" to finish]
**03:03:03 moose jávorszarvas**
hh:mm:ss foreign_word mother_tongue_word [or type "back" to finish]
**back**
Printing out the existing list with the newly recorded couples from ArrayList to the screen
[ 01:01:01 apple alma
,  02:02:02 hat sapka
,  03:03:03 moose jávorszarvas
]

Write list into file and close file.

Choose from the list: 
"new" for a new list or 
"exist" to continue an existing list or 
"back" to go back to main menu.
Command not recognized.
Choose from the list: 
"new" for a new list or 
"exist" to continue an existing list or 
"back" to go back to main menu.
**back**
Back to Main menu. 
Please enter a command: 
"input" or 
"list" or 
"search" or 
"end"
**end**
End of interaction.

**Comment by csabakoncz** [comment]
Thank you for the description, but what I meant is piece of code ("unit test") that demonstrates the problem in the production code. 
Most tests are written with JUnit:

https://dzone.com/articles/junit-tutorial-beginners
https://www.udemy.com/junit-tutorial-for-beginners-with-java-examples/

**Comment by Clearsight-github** [comment]
I will watch that course later.
I found and corrected the problem without JUint. This fault occured once again an other place in the code.
The problem is not clear to me but I had to use input.next(); instead of input.nextLine(); .
For some reason .nextLine() reads an empty row without stop to ask what the user want to write in system.in .
