### ISSUE TITLE
Project does not compile

### ISSUE THREAD

**Issue by csabakoncz** [Clearsight-github/DictionaryWithTime#9]
The package names have to be the same as the folder names (casing matters even on Windows)

I suggest to move the two classes to a common package that has a simple name (say, "dwt")

**Comment by Clearsight-github** [comment]
I know how to use package. I don't know why not compile on your machine.

**Comment by csabakoncz** [comment]
It seems to be an Eclipse-only problem.
Maven compiles the project

![image](https://cloud.githubusercontent.com/assets/7896191/25500626/1447dbd8-2b90-11e7-9ef5-d2e0d017d3eb.png)
